"""empty message

Revision ID: 78713572234f
Revises: 
Create Date: 2023-10-03 23:07:54.987711

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '78713572234f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_creator_relation')
    op.drop_table('playlist_song_association')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('playlist_song_association',
    sa.Column('playlist_id', sa.VARCHAR(length=36), nullable=True),
    sa.Column('song_id', sa.VARCHAR(length=36), nullable=True),
    sa.ForeignKeyConstraint(['playlist_id'], ['playlist.id'], ),
    sa.ForeignKeyConstraint(['song_id'], ['song.id'], )
    )
    op.create_table('user_creator_relation',
    sa.Column('id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('user_id', sa.VARCHAR(length=36), nullable=False),
    sa.Column('creator_id', sa.VARCHAR(length=36), nullable=False),
    sa.ForeignKeyConstraint(['creator_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('id')
    )
    # ### end Alembic commands ###
